total_timesteps: 150000

learning_rate: 0.0003
buffer_size: 100000
batch_size: 256
learning_starts: 1000
ent_coef: auto
target_entropy: auto
gamma: 0.95
tau: 0.005
train_freq: 1
gradient_steps: 1

eval_freq: 5000
n_eval_episodes: 20

num_final_eval_episodes: 100
success_threshold: 0.005

model_name: final_model #sac_fatch_reach_dense_V4

evaluation_model_label: auto_auto_150000_20260702-115209
